config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
  get '/posts/search', to: "posts#search", as: "search_path"

  resources :posts do
    get '/comments', to: "comments#comments_for_post"
    get '/next', to: "posts#next"
    get '/sentances', to: 'posts#get_sentance_content_for_post'
  end
  get '/users/logout', to: "users#logout", as: "logout_user"
  get '/users/login', to: "users#signin", as: "signin_user"
  post "/users/login", to: "users#login", as: "login_user"

  # Routes for Google authentication
  get "auth/:provider/callback", to: "users#googleAuth"
  get "auth/failure", to: redirect("/")
  get '/current_user', to: "application#get_current_user"
  resources :users do
    resources :posts, only: [:show, :new]
  end
  resources :sentances, only: [:create]
  resources :comments, only: [:create, :delete, :edit]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoryTime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Compiled and minified CSS -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

   <!-- Compiled and minified JavaScript -->

   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
   <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body>
    <nav>
      <div class="nav-wrapper blue-grey darken-2">
        <a href="<%= posts_path %>" class="brand-logo">Story Time</a>
        <ul id="nav-mobile" class="right down-on-med-and-down">
          <% if !logged_in? %>
            <li><a href="/users/new" >Sign Up</a></li>
            <li><a href= <%= signin_user_path %> >Login</a></li>
          <% else %>
            <li><%= link_to "New Story", new_post_path %></li>
            <li><%= link_to "Logout", logout_user_path %></li>
            <%= csrf_meta_tag %>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <h3 class = "red"><%= flash[:error] if flash[:error] %></h3>
      <%= yield %>
    </div>
    <br />
    <footer class="page-footer blue-grey darken-2">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Story Time</h5>
              </div>
              <div class="col l4 offset-l2 s12">
                <ul>
                  <li><a class="grey-text text-lighten-3" href="<%= logout_user_path %>">Logout</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2018 Harry Bloch
            </div>
          </div>
        </footer>

  </body>
</html>